version: '3'
services:
  frontend:
    build:
      context: ./client
      dockerfile: DockerFile
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: DockerFile
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

# sudo apt-get update
# sudo apt-get install docker.io -y
# sudo systemctl start docker
# sudo usermod -aG docker $USER

# docker build -t frontend-image .

# docker build -t backend-image .

# docker network create my-app-network

# docker run -d --name backend-container --network my-app-network -p 5000:5000 backend-image

# docker run -d --name frontend-container --network my-app-network -p 80:80 frontend-image

